### ISSUE TITLE
kitchen ec2 verifier broken

### ISSUE THREAD

**Issue by howdoicomputer** [chef/kitchen-inspec#106]
I already filed two tickets for this issue. Here are their references:

https://github.com/test-kitchen/test-kitchen/issues/1136
https://github.com/test-kitchen/kitchen-ec2/issues/281

**Comment by grv87** [comment]
I have the same problem. I'll  look at the code to try to find the source of the issue.

**Comment by siulcode** [comment]
@howdoicomputer  did you get to see a resolution for this problem? 

I need to run inspec tests into an ec2 instance created by kitchen-ec2, but tests seemed to be skipped completely.

**Comment by howdoicomputer** [comment]
@siulcode I don't think I did.

**Comment by bbscripps** [comment]
For the record, I've gotten this to work, but it does not work with the default file structure created with `chef generate cookbook`. I have another issue with SSH that I've worked around, but may file an issue over it.

Here's my information, if you want to try to get it working for you:
```
> chef --version
Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1
> tree
.
├── Berksfile
├── Berksfile.lock
├── README.md
├── chefignore
├── metadata.rb
├── recipes
│   └── default.rb
├── spec
│   ├── spec_helper.rb
│   └── unit
│       └── recipes
│           └── default_spec.rb
└── test
    └── smoke
        └── default
            ├── controls
            │   └── default_test.rb
            ├── inspec.lock
            └── inspec.yml

8 directories, 11 files
```
Basically, I had to move the default `test/smoke/default/default_test.rb` file into a `controls/` subdirectory, and add an _inspec.yml_ file. I'm attaching my _.kitchen.yml_ and _inspec.yml_ files.

[inspec.yml.txt](https://github.com/chef/kitchen-inspec/files/1145664/inspec.yml.txt)
[kitchen.yml.txt](https://github.com/chef/kitchen-inspec/files/1145665/kitchen.yml.txt)

**Comment by grv87** [comment]
My problem is gone, I figured out how to use `inspec` verifier with external profile.
Working code: https://github.com/FIDATA/infrastructure/blob/master/src/chef/.kitchen.yml#L62-L65

**Comment by adamleff** [comment]
Closing this issue as it appears to be resolved, and the `inspec_tests` parameter can be used to specify the exact tests to run, even when the default path structure expected by Test Kitchen isn't in use. If I'm incorrect about this being resolved, please let me know with specifics and I'll be happy to re-open.
