### ISSUE TITLE
Incorrect dependencies on 0.16 release

### ISSUE THREAD

**Issue by coderanger** [chef/kitchen-inspec#117]
[This patch](https://github.com/chef/kitchen-inspec/commit/b5a54527ddfb9cb4ae1ddf857fe189f7d2d61040) was included in 0.16, but that requires [functionality only added to InSpec in 0.34](https://github.com/chef/inspec/commit/85cbe713d7a5d4e2f3bb41f1376d5fccc15ebc4c). The current dependency on `kitchen-inspec` is `>= 0.22`, which is incorrect. We should yank the existing 0.16.0 and release a 0.16.1 with the correct InSpec dependency.

**Comment by coderanger** [comment]
Also re: why I am recommended a yank, I do some testing on older ChefDK's to ensure compat, so if we do a new release but don't remove the broken 0.16.0, bundler/rubygems will happily try installing that version instead of the fixed one.

**Comment by chris-rock** [comment]
Thanks for finding that issue @coderanger Would you like to put up a PR for that?

**Comment by coderanger** [comment]
The actual patch seemed easy enough to not be needed :) The complex bits are the new release and the yank.

**Comment by chris-rock** [comment]
Thanks @coderanger all fixed
