### ISSUE TITLE
Output file support for multiple platforms and multiple test suites

### ISSUE THREAD

**Issue by AgarFu** [chef/kitchen-inspec#121]
There is no way to retrieve the output of InSpec from kitchen when you have multiple platforms and multiple test suites in your kitchen setup.

For example if you have support for centos6 and centos7 and multiple test suites defined, default, datacenter1 and datacenter2 you'll have 6 InSpec executions so you'll have 6 different inspec output files but there is no way to specify them.

**Comment by adamleff** [comment]
This appears to be resolved in #122.
