### ISSUE TITLE
chef exec kitchen verify fails for inspec tests

### ISSUE THREAD

**Issue by chef1729** [chef/kitchen-inspec#132]
Please look into this. My kitchen inspec fails. Test come out green but at the end it says none of the tests are run.

-bash-4.2$ chef exec kitchen verify
-----> Starting Kitchen (v1.15.0)
W, [2017-04-20T13:29:08.148899 #20507]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#frozen? defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-20T13:29:08.149023 #20507]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#frozen? defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-20T13:29:08.149072 #20507]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#frozen? defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-20T13:29:08.167121 #20507]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-20T13:29:08.167185 #20507]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
WARN: Unresolved specs during Gem::Specification.reset:
      term-ansicolor (>= 0)
      excon (>= 0.38.0)
      rainbow (~> 2)
      unf_ext (>= 0)
      ffi (>= 1.0.1)
      diff-lcs (< 2.0, >= 1.2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Verifying <default-windows-2012R2>...
       Loaded
       Loaded
[DEPRECATION] `contain` matcher. Please use the following syntax `its('content') { should include('value') }`.
[DEPRECATION] `contain` matcher. Please use the following syntax `its('content') { should include('value') }`.
[DEPRECATION] `contain` matcher. Please use the following syntax `its('content') { should include('value') }`.
[DEPRECATION] `contain` matcher. Please use the following syntax `its('content') { should include('value') }`.

Target:  winrm://administrator@http://10.75.140.118:5985/wsman:3389

  File c:\tmp\serverspec\node.json
     ✔  should be file
     ✔  content should contain "logs_to_splunk"
     ✔  content should contain "application"
  File c:\Program
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*D:\\PGM\\MonitoringData\\services.json/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*D:\\PGM\\MonitoringData\\ValidateViews.json/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*D:\\PGM\\MonitoringData\\spwho.json/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*D:\\PGM\\MonitoringData\\InformationSchemaViews.json/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*D:\\PGM\\MonitoringData\\ExistingBDMViews.json/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*E:\\SQL2012\\Program Files\\Microsoft SQL Server\\MSRS11.MSSQLSERVER\\Reporting Services\\LogFiles\\ReportServerService.*/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*E:\\SQL2012\\Program Files\\Microsoft SQL Server\\MSSQL11.MSSQLSERVER\\MSSQL\\Log\\ERRORLOG.*/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*E:\\SQL2012\\Program Files\\Microsoft SQL Server\\MSSQL11.MSSQLSERVER\\MSSQL\\Log\\SQLAGENT.*/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*E:\\SQL2012\\Program Files\\Microsoft SQL Server\\MSAS11.MSSQLSERVER\\OLAP\\Log\\msmdsrv.log/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*E:\\SQL2012\\Program Files\\Microsoft SQL Server\\MSAS11.TABULAR\\OLAP\\Log\\msmdsrv.log/
     ✔  Files\SplunkUniversalForwarder\etc\apps\radian_forwarder\local\inputs.conf content should match /.*R:\\SplunkData\\.*/

Target:  winrm://administrator@http://10.75.140.118:5985/wsman:3389

     No tests executed.

Test Summary: 14 successful, 0 failures, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `[]=' for nil:NilClass] on default-windows-2012R2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

-bash-4.2$

**Comment by pantocrator27** [comment]
Can you supply your .kitchen.yml file?

**Comment by adamleff** [comment]
There has not been any movement on this issue in quite some time, so I'm going to close it for now. I'm happy to reopen it when we have more repro steps. Thanks!
