### ISSUE TITLE
Failed to complete #verify action: [no implicit conversion of nil into String]

### ISSUE THREAD

**Issue by pantocrator27** [chef/kitchen-inspec#135]
It appears that when I run test-kitchen using the concurrency flag, I periodically receive a `Failed to complete #verify action: [no implicit conversion of nil into String]`.  This appears to be a race condition as it does not happen every time.  It just periodically occurs about 50% of the time.

**Comment by pantocrator27** [comment]
Seems to be related to https://github.com/chef/inspec/issues/1598

**Comment by pantocrator27** [comment]
Also seems to be related to https://github.com/chef/kitchen-inspec/issues/119

**Comment by adamleff** [comment]
Duplicate of #119
