### ISSUE TITLE
False attribute value is not initializing

### ISSUE THREAD

**Issue by devops42** [chef/kitchen-inspec#138]
File `.kitchen.yml`
```
...
    verifier:
      attributes:
        val_true: true
        val_false: false
...
```

File test.rb
```
val_true = attribute('val_true', description: "true value")
val_false = attribute('val_false', description: "false value")

puts "val_true=#{val_true.class}"
puts "val_false=#{val_false.class}"
```

And output:
```
val_true=TrueClass
val_false=NilClass
```

Any ideas why `val_false` in not initializing as FalseClass?

**Comment by adamleff** [comment]
@devops42, thanks for submitting this issue, and sorry for the delay in responding. I've been able to reproduce this behavior in InSpec core without the use of kitchen-inspec, so I've created a new issue (chef/inspec#2164) to track this and I'll see if I can't fix it relatively quickly.

I'm closing this issue in favor of the new issue opened in chef/inspec. Thanks!
