### ISSUE TITLE
Option to specify path to Inspec test with kitchen-inspec

### ISSUE THREAD

**Issue by AnotherWorkingNerd** [chef/kitchen-inspec#139]
### Description

Currently, with kitchen-inspec the inspec tests are supposed to be in a fixed location in test/integration/default/<suite>.  it would be nice if the path could be specified instead of being forced into test/integration/default/

### InSpec and Platform Version

0.19

### Replication Case

see description. This issue was entered at the request of @chris-rock after some slack conversation with myself and slack member 'eulipion'

### Possible Solutions

Option or setting to point to inspec test location.

**Comment by AnotherWorkingNerd** [comment]
this may be a duplicate of https://github.com/chef/kitchen-inspec/issues/70

**Comment by adamleff** [comment]
kitchen-inspec supports the `inspec_tests` verifier configuration parameter which accepts a variety of test path formats, including local and remote. There are some examples in the project README.

To simply point to a different path in your cookbook or similar structure:

```yaml
verifier:
  inspec_tests:
    - path/to/profile1
    - path/to/profile2
```

You can use both relative and absolute paths. The only gotcha here is that these are expected to be InSpec profiles at these paths, not just a collection of `*_spec.rb` files with tests in them. It's very easy to convert a set of test files to an InSpec profile, however.
