### ISSUE TITLE
Failures should be tagged with the instance they failed against

### ISSUE THREAD

**Issue by smurawski** [chef/kitchen-inspec#30]
When running against multiple nodes, the last node seems to aggregate the failure output, but not flag which node they were really from.

**Comment by chris-rock** [comment]
@smurawski Which version of kitchen-inspec are you running. We fixed a couple of issues around that topic in `inspec` and `kitchen-inspec`

**Comment by chris-rock** [comment]
We fixed this with the latest version of `inspec` and `kitchen-inspec`. Please update to the latest versions.  See https://github.com/chef/inspec/pull/320

Please reopen if this still persists with the latest versions
