### ISSUE TITLE
show test and result in the log

### ISSUE THREAD

**Issue by cjohannsen81** [chef/kitchen-inspec#44]
Hey, would it be possible to show the test and the result as it is with serverspec:

```
    File "/etc/apache2/httpd.conf"
       should exist
     Port "80"
       should be listening
     Command "curl http://localhost"
       stdout
         should match /Hello/

   Finished in 0.13462 seconds (files took 0.33277 seconds to load)
   3 examples, 0 failures
```

**Comment by chris-rock** [comment]
Hi @cjohannsen81 You can specify the `--format` as introduced in #27. Currently we use `--format progress` as default, but you could switch to `--format documentation`

**Comment by benjamink** [comment]
:+1:  How is the`--format` option passed in the `.kitchen.yml` file?

**Comment by chris-rock** [comment]
#26
