### ISSUE TITLE
InSpec Profile

### ISSUE THREAD

**Issue by postgred** [chef/kitchen-inspec#46]
Hi. Can I use InSpec Profile? https://github.com/chef/inspec/blob/master/docs/profiles.rst 
Where should I create directory for profiles?

I tried create profile in `test/controls/*` and ran `include_conrtols 'name'` in my test, but control not started.

**Comment by chris-rock** [comment]
@postgred Thanks for bringing up this question. We will improve the InSpec profile support in `kitchen-inspec` over the next weeks. For now, you are able to use one profile only. That profile needs to be located in `test/integration/%suitename%`

```
└── test
    └── integration
        └── default
            ├── controls
            │   ├── your_spec.rb
            └── inspec.yml
```

**Comment by chris-rock** [comment]
@postgred This should be solved with the latest version of kitchen-inspec. Please reopen, if the issue persists.
