### ISSUE TITLE
Colo[u]r those dots and Fs!

### ISSUE THREAD

**Issue by jjasghar** [chef/kitchen-inspec#62]
It's pretty common now to see colo[u]rs for "." and "F"s in tests.

I'd like to ask that this is added to the runs, so something like the following would be colo[u]red.

```
       Search `/Users/jasghar/repo/cookbooks/hipchat-chef-plugin-cookbook/test/integration/default` for tests
......FF........

Failures:
```

This would also put the Failures in RED so you can could identify issues quickly.

**Comment by chris-rock** [comment]
InSpec has this feature now https://github.com/chef/inspec/pull/523

**Comment by adamleff** [comment]
Feature implemented, closing issue.
