### ISSUE TITLE
Unable to test installed Gems

### ISSUE THREAD

**Issue by cullenmcdermott** [chef/kitchen-inspec#65]
Hi,

I need to test that some Gems are installed(they have been installed via the `chef_gem`. However it looks like kitchen-inspec isn't able to pick up on any gem installation. In order to try and track down this issue I ended up installing rvm and some test gems to see if inspec would return those, it didn't seem to help. However I noticed when I ran `inspec exec test/integration/server/default.rb -t ssh://vagrant@192.168.50.10 --password 'vagrant'` it would seem to find my rvm gempath correctly. But this doesn't help my original issue of inspec not picking up on chef gems not being seen.

I'm not sure if this is an issue with inspec, kitchen-inspec  or some misconfiguration on my end. Any advice to point me in the right direction would be great!

Thanks!

**Comment by cullenmcdermott** [comment]
Nevermind on this, I realized this was probably out of the scope of this project

**Comment by srenatus** [comment]
@cullenmcdermott Well, actually, having a possibility to specify [which `gem` to use for the `gem` resource](https://github.com/chef/inspec/blob/master/lib/resources/gem.rb#L22), similar to [the way you can override service manager binaries](https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L723-L726) would totally make sense.

PR's are very welcome, but it should go against inspec then :+1:
