### ISSUE TITLE
kitchen converge fails on ubuntu

### ISSUE THREAD

**Issue by pavank1933** [chef/kitchen-inspec#81]
**Local gem list goes this way:-
kitchen-ec2 (1.0.0)
kitchen-inspec (0.12.5)
kitchen-vagrant (0.20.0)
test-kitchen (1.6.0)**

**Still facing the following issue**
```
pavan@ubuntu:~/sample/git-cookbook$ kitchen converge
-----> Starting Kitchen (v1.6.0)
-----> Converging <default-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Preparing current project directory as a cookbook
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [undefined method `encoding' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by cjohannsen81** [comment]
@pavank1933 Please provide your .kitchen.yml file and as far as I can see the converge is done on a default-windows-2012r not Ubuntu, right?

**Comment by chris-rock** [comment]
In addition to @cjohannsen81 comment, it seems that this error has nothing to do with kitchen-inspec. The converge is the chef converge. The first thing I would try is to update to the latest version of test-kitchen (e.g. 1.8.0).

**Comment by chris-rock** [comment]
@pavank1933 I am going to close this issue. Please reopen if the issue persists.

**Comment by pavank1933** [comment]
Surely thanq
