### ISSUE TITLE
How to verify with a local profile

### ISSUE THREAD

**Issue by mhedgpeth** [chef/kitchen-inspec#88]
I would like my verifier to go against a local profile that is available on my hard drive. Something like:

```
verifier: inspec
  profile: ../../profiles/my-profile
```

Is this currently possible?

**Comment by mhedgpeth** [comment]
Addressed through updated documentation, thanks.

**Comment by chris-rock** [comment]
Thanks @mhedgpeth for highlighting the missing information. We added that with #89
