### ISSUE TITLE
Default to ( progress | documentation ) format for test-kitchen inspec verifier

### ISSUE THREAD

**Issue by brentm5** [chef/kitchen-inspec#91]
It looks like the default inspec format for output has changed to not be as helpful when issues show up.  For example lets say you have something like this:

```
describe file('/home/me/.ssh') do
  it { should exist }
  it { should be_file }
end
```

That would output a single line 

```
✔  File /home/me/.ssh should exist

# And then a bunch of error with no context
... Blah
```

Not sure if this is something I am doing wrong on my system.  Using inspec as a verifier is something we are trying to switch to but I would rather not add the following below:

```
verifier:
  name: inspec
  format: progress # <- This
```

Just trying to start a discussion on this, I can do the code.  I believe it will be one line but not going to do that if its a waste of time and no one agrees.

**Comment by chris-rock** [comment]
@bigbam505 Thanks a lot for your feedback. This is very interesting, because most users complaint about the progress/documentation formatters, therefore simply changing the default formatter will not do the trick.
We are interested in improving the current InSpec formatter to address your use case. Please propose your ideas and name shortcomings of the InSpec formatter at https://github.com/chef/inspec/issues/532

**Comment by brentm5** [comment]
@chris-rock Thanks I will look at that issue.

**Comment by chris-rock** [comment]
@brentm5 We did a couple of improvement in InSpec 0.29.0 with the fix of https://github.com/chef/inspec/issues/812 If the issue still persists, please let me know

**Comment by brentm5** [comment]
That was really my complaint.  Overall the format of the default output is fine from my standpoint.  It was just tests failing overall but showing all green in the output when running inspec.  Ill see if this fixes my issue  and if it does then I will close this as this is just a duplicate of chef/inspec#812 in my eyes.

**Comment by brentm5** [comment]
It is not the best view for the errors but it has been corrected so you can see the actual error with whats causing the issue so I consider this resolved.

**Comment by chris-rock** [comment]
@brentm5 Could you add a ticket in InSpec to report what is missing and what you would expect?
